function output = crop_center(input, output_size)
    output = input(...
    ceil(end/2 - output_size(1)/2 + 1:end/2 + output_size(1)/2),...
    ceil(end/2 - output_size(2)/2 + 1:end/2 + output_size(2)/2));
end
