function output = crop_center(input,outputSize)
    output = input(...
    ceil(end/2 - outputSize(1)/2 + 1:end/2 + outputSize(1)/2),...
    ceil(end/2 - outputSize(2)/2 + 1:end/2 + outputSize(2)/2));
end